#!/usr/bin/env python
# coding: utf-8

# ### Importing Libraries

# In[1]:


import numpy as np 
import pandas as pd 


# ### Load Datasets

# In[2]:


path = "/Users/aakritigautam/Downloads/climate_change_impact_on_agriculture_2024.csv"


# In[3]:


climate_impact_df = pd.read_csv(path)
climate_impact_df


# ### Data Exploration and Cleaning

# #### Display column names:

# In[5]:


climate_impact_df.columns


# #### Display DataFrame information:

# In[6]:


climate_impact_df.info()


# #### Describe the data its mean, median standard deviation and soon..

# In[7]:


climate_impact_df.describe()


# #### Find any missing values

# In[10]:


climate_impact_df.replace(['', ' ', '-', 'N/A', 'na', '?'], np.nan, inplace=True)
climate_impact_df.isnull().sum()


# In[ ]:




